export { default as HomePage } from "./Home";
export { default as ErrorPage } from "./Error";
export { default as About } from "./About";
export { default as Products } from "./Products";
export { default as Services } from "./Services";
export {default as Terms} from "./Terms";
export {default as RefundPolicy} from "./RefundPolicy";
export {default as PrivacyPolicy} from "./PrivacyPolicy";
export {default as AllPerfumes} from "./AllPerfumes";
export {default as CancellationPolicy} from "./CancellationPolicy";
export {default as Gifts} from "./Gifts";
